[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "porthunter"
version = "0.1.0"
description = "PortHunter MCP (stdio) + CLI integrados para análisis de PCAP"
readme = "README.md"
requires-python = ">=3.10"
authors = [{ name = "José Gramajo" }]
license = { text = "MIT" }
dependencies = [

]

[tool.setuptools]
# Mapea el paquete "porthunter" que vive dentro de server/porthunter_mcp
packages = { find = { where = ["server/porthunter_mcp"] } }

[tool.setuptools.package-dir]
"" = "server/porthunter_mcp"

